### ISSUE TITLE
Suspend icon hardly visible

### ISSUE THREAD

**Issue by FWDekker** [Zren/plasma-applet-tiledmenu#41]
The suspend icon under the power options is hard to see unless it is hovered over.

When the suspend entry is not hovered over it looks like this:
![Without hovering](https://user-images.githubusercontent.com/13442533/53968192-e1722f00-40f6-11e9-875f-6d33f0dd7c67.png)

When the suspend entry is hovered over it looks like this:
![With hovering](https://user-images.githubusercontent.com/13442533/53968216-ea630080-40f6-11e9-9a0c-f27fe1c90357.png)

I think it would help if the suspend icon were made brighter.

### Version information
```
OS      Kubuntu 18.04 (x64)
Plasma  5.12.7
```

**Comment by Zren** [comment]
That icon is chosen by your desktop theme (Breeze). `/usr/share/plasma/desktoptheme/default/icons/system.svgz`

Kubuntu Bionic 18.04 only has v5.44 of `plasma-frameworks` package (which contains the breeze desktop theme).

* https://repology.org/project/plasma-framework/versions
* https://packages.ubuntu.com/source/bionic/plasma-framework

The current icon has been fixed in later versions (looks fine in 5.55 for me). Also, 5.56 has a new icon as it's been renamed "Sleep".

https://github.com/KDE/plasma-framework/blob/master/src/desktoptheme/breeze/icons/system.svgz

If you download `system.svgz` from v5.44, you'll see that while `id="22-22-system-suspend"` has `style="fill:currentColor;"` and `class="ColorScheme-Text"`, it also has `color:#31363b;` which probably overrides using the "color scheme's `currentColor`.

https://github.com/KDE/plasma-framework/blob/v5.44.0/src/desktoptheme/breeze/icons/system.svgz

**Comment by FWDekker** [comment]
Aha, I didn't know that. Thanks for the information!
